---
title: "Socioeconomic GIS"
author: "Rueichen Tsai"
date: "2024-04-22"
output: html_document
---

### set up and load libraries

```{r}
setwd("D:/CP6570 Socioeconomic GIS/FinalProject")
library(tidyverse)
library(dplyr)
library(vtable)
library(jtools)
library(car)
```


### read in data

```{r}
# target data with census tract id
df <- read.csv("CensusTract_Regression.csv")

# join data: at the census tract level
UERate <- read.csv("UERate.csv") # unemployment rate variable, DP03_0009E
pubinc <- read.csv("pubinc.csv") # household with public assistance income (cash assistance and social insurance)
edu <- read.csv("EduAttain.csv") # percent population a Bachelor's degree
mg <- read.csv("hsmortg.csv") # percent household with a mortgage

# join data: at the zip code level
est <- read.csv("ct_est.csv") # number of business establishment
```

### data cleaning
```{r}
# keep 11-digit census tract id
UERate$GEOID <- substring(UERate$GEOID, 10)
pubinc$GEOID <- substring(pubinc$GEOID, 10)
edu$GEOID <- substring(edu$GEOID, 10)
mg$GEOID <- substring(mg$GEOID, 10)

# select interest columns only
est <- select(est, GEOID, zcta_est)

# convert variable to numeric
UERate$UERate <- as.numeric(UERate$UERate)

# Merge data (educational attainment, public assistance income, unemployment rate, mortgage)
df <- merge(df, edu, by = "GEOID")
df <- merge(df, pubinc, by = "GEOID")
df <- merge(df, UERate, by = "GEOID")
df <- merge(df, mg, by = "GEOID")
df <- merge(df, est, by = "GEOID")

# percent population with a bachelor's degree
df$B.pct <- (df$B / (df$LHSD + df$HSD + df$SC + df$B)) * 100

# percent owner-occupied housing units with a mortgage 
df$mgpct <- (df$hsmort / df$totocc) * 100


# low-paying job access index
df$Norm_AC <- (df$AC - min(df$AC, na.rm=TRUE)) / (max(df$AC, na.rm = TRUE) - min(df$AC, na.rm = TRUE))

# percent household with public assistance income
df$PubincPct <- (df$pubinc / df$tot) * 100

# percent household without a vehicle (this variable is extracted from lab2)
df$NoCar <- df$NoCar * 100

# low-paying jobs to low income workers ratio
df$lowratio <- df$LowInc_job/df$LowInc_worker

# low-paying jobs dissimilarity
df$LowIncJob_DI <- abs((df$UE / sum(df$UE, na.rm = TRUE)) - (df$LowInc_job / sum(df$LowInc_job, na.rm = TRUE))) / 2 * 100

df$Norm_LPDI <- (df$LowIncJob_DI - min(df$LowIncJob_DI, na.rm = TRUE)) / (max(df$LowIncJob_DI, na.rm = TRUE) - min(df$LowIncJob_DI, na.rm = TRUE))

# initial dissimilarity
df$before_diff <- (df$UE / sum(df$UE, na.rm = TRUE)) - (df$LowInc_job / sum(df$LowInc_job, na.rm = TRUE))

# number of people need to relocated from each tract
#(positive value = number of pp need to move out from that area, vice versa)
df$pp_need_relocate <- round(sum(df$UE, na.rm=TRUE) * df$before_diff)

# number of people in each tract after relocation
df$after_pop <- df$UE - df$pp_need_relocate

# dissimilarity after people relocate
df$after_diff <- (df$after_pop / sum(df$after_pop, na.rm=TRUE)) - 
  (df$LowInc_job / sum(df$LowInc_job, na.rm = TRUE))

# before and after job-pop ratio
df$before_job_pop_ratio <- sum(df$LowInc_job, na.rm = TRUE) / sum(df$UE, na.rm = TRUE)
df$after_job_pop_ratio <- sum(df$LowInc_job, na.rm = TRUE) / sum(df$after_pop)

# ideal job-pop ratio
df$ideal <- sum(df$before_job) / sum(df$before_pop)

#test
test <- select(df, UE, LowInc_job, before_diff, pp_need_relocate, after_pop, after_diff)
```


### imput missing values

```{r}
# if the number of missing values in a interest variables are smaller than ten percent of total observations, then replace it with median value from that interest variable

if ((sum(is.na(df$UERate)) / nrow(df)) <= 0.1) {
  a <- na.omit(df$UERate) 
  median_value <- median(a)
  df$UERate[is.na(df$UERate)] <- median_value
}

if ((sum(is.na(df$B.pct)) / nrow(df)) <= 0.1) {
  a <- na.omit(df$B.pct)
  median_value <- median(a)
  df$B.pct[is.na(df$B.pct)] <- median_value
}

if ((sum(is.na(df$mgpct)) / nrow(df)) <= 0.1) {
  a <- na.omit(df$mgpct)
  median_value <- median(a)
  df$mgpct[is.na(df$mgpct)] <- median_value
}

if ((sum(is.na(df$NoCar)) / nrow(df)) <= 0.1) {
  a <- na.omit(df$NoCar) 
  median_value <- median(a)
  df$NoCar[is.na(df$NoCar)] <- median_value
}

if ((sum(is.na(df$PubincPct)) / nrow(df)) <= 0.1) {
  a <- na.omit(df$PubincPct) 
  median_value <- median(a)
  df$PubincPct[is.na(df$PubincPct)] <- median_value
}

if ((sum(is.na(df$Norm_AC)) / nrow(df)) <= 0.1) {
  a <- na.omit(df$Norm_AC) 
  median_value <- median(a)
  df$Norm_AC[is.na(df$Norm_AC)] <- median_value
}

if ((sum(is.na(df$LowIncJob_DI)) / nrow(df)) <= 0.1) {
  a <- na.omit(df$LowIncJob_DI) 
  median_value <- median(a)
  df$LowIncJob_DI[is.na(df$LowIncJob_DI)] <- median_value
}

if ((sum(is.na(df$lowratio)) / nrow(df)) <= 0.1) {
  a <- na.omit(df$lowratio) 
  median_value <- median(a)
  df$lowratio[is.na(df$lowratio)] <- median_value
}

if ((sum(is.na(df$zcta_est)) / nrow(df)) <= 0.1) {
  a <- na.omit(df$zcta_est) 
  median_value <- median(a)
  df$zcta_est[is.na(df$zcta_est)] <- median_value
}

if ((sum(is.na(df$Norm_LPDI)) / nrow(df)) <= 0.1) {
  a <- na.omit(df$Norm_LPDI) 
  median_value <- median(a)
  df$Norm_LPDI[is.na(df$Norm_LPDI)] <- median_value
}

if ((sum(is.na(df$pp_need_relocate)) / nrow(df)) <= 0.1) {
  a <- na.omit(df$pp_need_relocate) 
  median_value <- median(a)
  df$pp_need_relocate[is.na(df$pp_need_relocate)] <- median_value
}
```



### rename variables
```{r}
# rename field names
df <- df %>% 
  rename(c(BAPct=B.pct, MortgPct=mgpct, AI=Norm_AC, NoCarPct=NoCar, LPJD = LowIncJob_DI, LPJR=lowratio))

# select interest variables only
reg <- select(df, GEOID, UERate, BAPct, MortgPct, NoCarPct, PubincPct, AI, LPJD, LPJR, Norm_LPDI, pp_need_relocate)
```


### build regression model
```{r}
model <- lm(UERate ~
                  BAPct
                + MortgPct
                + NoCarPct
                + PubincPct
                + AI
                + LPJD
                + LPJR
                + pp_need_relocate
                , data = reg)
summary(model)
```


### export data for mapping
```{r}
#write.csv(reg, "clean_regression.csv")
```

### descriptive statistics table
```{r}
statstab <- reg
statstab$GEOID <- NULL
st(statstab)
```


### data exploration: race-specific model
```{r}
# explains very little variable about unemployment rate, thus, not including in the presentation slides
race <- read.csv("uer_by_race_cleaned.csv")

new <- merge(reg, race, by = "GEOID")

new$white <- as.numeric(new$white)
model_white <- lm(white ~
                  BAPct
                + MortgPct
                + NoCarPct
                + PubincPct
                + AI
                + LPJD
                + LPJR
                , data = new)
summary(model_white)

new$black <- as.numeric(new$black)
model_black <- lm(black ~
                  BAPct
                + MortgPct
                + NoCarPct
                + PubincPct
                + AI
                + LPJD
                + LPJR
                , data = new)
summary(model_black)

new$asian <- as.numeric(new$asian)
model_asian <- lm(asian ~
                  BAPct
                + MortgPct
                + NoCarPct
                + PubincPct
                + AI
                + LPJD
                + LPJR
                , data = new)
summary(model_asian)

new$hispanic <- as.numeric(new$hispanic)
model_hispanic <- lm(hispanic ~
                  BAPct
                + MortgPct
                + NoCarPct
                + PubincPct
                + AI
                + LPJD
                + LPJR
                , data = new)
summary(model_hispanic)
```


